const occupation = [
  'Soldier',
  'FortuneSeeker',
  'Bandit',
  'SlaveTrader',
  'TreasureHunter',
  'Beggar',
  'Actor',
  'Lumberjack',
  'Hunter',
  'Farmer',
  'Laborer',
  'Jester',
  'Wanderer',
  'Fisher',
  'Noble',
  'Child',
  'Trader',
  'Brewer',
  'Carpenter',
  'Apprentice',
  'Thief',
  'Druid',
  'Baker',
  'Refugee',
  'Assassin',
  'Smith',
  'Gravedigger',
  'RustBrother',
  'Shepherd',
  'Braggart',
  'Cook',
  'Cultist',
  'Guard',
  'Messenger',
  'Miner',
  'Academic',
] as const

export type Occupation = (typeof occupation)[number]

export const getOccupations = (): Occupation[] => [...occupation]
